<?php
declare(strict_types=1);
require __DIR__ . '/../app/bootstrap.php';
use App\Core\Router;
use App\Controllers\AuthController;
use App\Controllers\PartsController;
use App\Controllers\InventoryController;
use App\Controllers\SetsController;
use App\Controllers\ApiController;
use App\Controllers\SyncController;
$router = new Router();
$router->add('GET', '/', [PartsController::class, 'home']);
$router->add('GET', '/login', [AuthController::class, 'loginForm']);
$router->add('POST', '/login', [AuthController::class, 'login']);
$router->add('GET', '/logout', [AuthController::class, 'logout']);
$router->add('GET', '/register', [AuthController::class, 'registerForm']);
$router->add('POST', '/register', [AuthController::class, 'register']);
$router->add('GET', '/parts', [PartsController::class, 'index']);
$router->add('GET', '/parts/view', [PartsController::class, 'view']);
$router->add('POST', '/parts/create', [PartsController::class, 'create']);
$router->add('POST', '/parts/update', [PartsController::class, 'update']);
$router->add('POST', '/parts/delete', [PartsController::class, 'delete']);
$router->add('GET', '/inventory', [InventoryController::class, 'index']);
$router->add('POST', '/inventory/update', [InventoryController::class, 'update']);
$router->add('GET', '/inventory/export', [InventoryController::class, 'export']);
$router->add('POST', '/inventory/import', [InventoryController::class, 'import']);
$router->add('GET', '/search', [PartsController::class, 'search']);
$router->add('GET', '/sets', [SetsController::class, 'index']);
$router->add('GET', '/sets/view', [SetsController::class, 'view']);
$router->add('POST', '/sets/create', [SetsController::class, 'create']);
$router->add('POST', '/sets/update', [SetsController::class, 'update']);
$router->add('POST', '/sets/delete', [SetsController::class, 'delete']);
$router->add('POST', '/sets/favorite', [SetsController::class, 'favorite']);
$router->add('GET', '/sets/missing', [SetsController::class, 'missing']);
$router->add('GET', '/api/parts', [ApiController::class, 'parts']);
$router->add('GET', '/api/sets', [ApiController::class, 'sets']);
$router->add('GET', '/api/inventory', [ApiController::class, 'inventory']);
$router->add('GET', '/api/suggest', [ApiController::class, 'suggest']);
$router->add('POST', '/sync/bricklink', [SyncController::class, 'syncBrickLink']);
$router->dispatch();
