<?php
declare(strict_types=1);
require __DIR__ . '/../app/bootstrap.php';
use App\Core\Router;
use App\Controllers\PartsController;
use App\Controllers\AuthController;
use App\Controllers\InventoryController;
use App\Controllers\SetsController;
use App\Controllers\ApiController;
use App\Controllers\UpdateController;
use App\Controllers\ConfigController;
use App\Controllers\SyncController;
$router = new Router();
$router->add('GET', '/', [PartsController::class, 'home']);
$router->add('GET', '/index.php', [PartsController::class, 'home']);
$router->add('GET', '/login', [AuthController::class, 'loginForm']);
$router->add('POST', '/login', [AuthController::class, 'login']);
$router->add('GET', '/logout', [AuthController::class, 'logout']);
$router->add('GET', '/register', [AuthController::class, 'registerForm']);
$router->add('POST', '/register', [AuthController::class, 'register']);
$router->add('GET', '/parts', [PartsController::class, 'index']);
$router->add('GET', '/parts/view', [PartsController::class, 'view']);
$router->add('POST', '/parts/create', [PartsController::class, 'create']);
$router->add('POST', '/parts/update', [PartsController::class, 'update']);
$router->add('POST', '/parts/delete', [PartsController::class, 'delete']);
$router->add('GET', '/inventory', [InventoryController::class, 'index']);
$router->add('POST', '/inventory/update', [InventoryController::class, 'update']);
$router->add('POST', '/inventory/updateDetails', [InventoryController::class, 'updateDetails']);
$router->add('GET', '/inventory/export', [InventoryController::class, 'export']);
$router->add('POST', '/inventory/import', [InventoryController::class, 'import']);
$router->add('GET', '/search', [PartsController::class, 'search']);
$router->add('GET', '/sets', [SetsController::class, 'index']);
$router->add('GET', '/sets/view', [SetsController::class, 'view']);
$router->add('POST', '/sets/create', [SetsController::class, 'create']);
$router->add('POST', '/sets/update', [SetsController::class, 'update']);
$router->add('POST', '/sets/delete', [SetsController::class, 'delete']);
$router->add('POST', '/sets/favorite', [SetsController::class, 'favorite']);
$router->add('GET', '/sets/missing', [SetsController::class, 'missing']);
$router->add('GET', '/api/parts', [ApiController::class, 'parts']);
$router->add('GET', '/api/sets', [ApiController::class, 'sets']);
$router->add('GET', '/api/inventory', [ApiController::class, 'inventory']);
$router->add('GET', '/api/suggest', [ApiController::class, 'suggest']);
$router->add('GET', '/admin/update', [UpdateController::class, 'page']);
$router->add('POST', '/admin/update/backup', [UpdateController::class, 'backup']);
$router->add('POST', '/admin/update/apply', [UpdateController::class, 'apply']);
$router->add('POST', '/admin/update/clear_db', [UpdateController::class, 'clearDb']);
$router->add('POST', '/admin/update/verify_schema', [UpdateController::class, 'verifySchema']);
$router->add('GET', '/admin/config', [ConfigController::class, 'page']);
$router->add('POST', '/admin/config/seed_colors', [ConfigController::class, 'seedColors']);
$router->add('POST', '/admin/config/seed_parts', [ConfigController::class, 'seedParts']);
$router->add('POST', '/admin/config/seed_sets', [ConfigController::class, 'seedSets']);
$router->add('POST', '/admin/config/scrape_parts_one', [ConfigController::class, 'scrapePartsOne']);
$router->add('POST', '/admin/config/scrape_sets_one', [ConfigController::class, 'scrapeSetsOne']);
$router->add('POST', '/sync/bricklink', [SyncController::class, 'syncBrickLink']);
$router->add('POST', '/sync/bricklink_set', [SyncController::class, 'syncBrickLinkSet']);
$router->dispatch();
